# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RobiBase
email: bonjour@a10s.ca
subtitle: Une expérience ludique autour de l'oeuvre pandémique de Damien Robitaille
description: >- # this means to ignore newlines until "baseurl:"
  RobiBase est un projet de A10s servant à explorer le potentiel du web
  sémantique et des solutions de développement d'applications «no-code».
  C'est aussi notre façon de rendre hommage à l'incroyable travail de
  Damien Robitaille depuis le début de la pandémie de COVID-19.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: a10s_ca
github_username:  a10s-ca

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

permalink: /videos/:year/:month/:day/:slug:output_ext

search: true
paginate: 5

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

locale: "fr-CA"

footer:
  links:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
